<?php

return [
    "permissions" => [
        "الدردشة كما drtech" => "chat_as_drtech",
        "تحديث الخدمة" => "update_service",
        "تعيين رسالة كمنع" => "set_message_as_prevent",
        "تعيين الطلب كمكتمل" => "set_order_complete",
        "تعيين الطلب في الإنتظار" => "set_order_waiting",
        "تعيين الطلب كمعلق" => "set_order_pending",
        "تعيين الطلب كملغي" => "set_order_cancel",
        "اتصل بالمستخدم من تفاصيل الطلب" => "call_user_from_order_details",
        "دردشة المستخدم من تفاصيل الطلب" => "chat_user_from_order_details",
        "الإتصال بالمستخدم من الطلبات" => "call_user_from_orders",
        "مستخدم الدردشة من الطلبات" => "chat_user_from_orders",
        "الدردشة من تفاصيل المستخدم" => "chat_from_user_details",
        "مزود whatsapp من الطلب" => "whatsapp_provider_from_order",
        "مستخدم whatsapp من الطلب" => "whatsapp_user_from_order",
        "تعيين أعلى دبوس الخدمة" => "set_service_pin_top",
        "قبول الخدمة" => "accept_service",
        "رفض الخدمة" => "reject_service",
        "الخدمة المعلقة" => "pending_service",
        "حظر المستخدم" => "set_user_block",
        "التحقق من البريد الإلكتروني للمستخدم" => "set_user_email_verified",
        "التحقق من المستخدم" => "set_user_verified",
        "التحقق من هوية المستخدم" => "set_user_identity_verified",
        "تعيين المستخدم كمفعل او مشغول" => "set_user_active_busy",
        "التحول إلى المزود او المراقب" => "switch_as_provider_or_monitor",
        "تغيير حالة التبليغ" => "change_state_reports",
        "تغيير حالة طلبات السحب" => "change_state_withdraw_request",
        "تغيير الصلاحيات" => "change_permission",
        "رؤية صفحة الطلبات" => "show_order_page",
        "رؤية صفحة المراسلة" => "show_chat_page",
        "رؤية صفحة طلبات السحب" => "show_withdraw_page",
        "رؤية صفحة الإشعارات" => "show_notification_page",
        "رؤية صفحة البلاغات" => "show_report_page",
        "رؤية صفحة الخدمات" => "show_service_page",
        "رؤية صفحة المستخدمين" => "show_user_page",
    ]
];
