<?php return  [ "We Tech",
    "Skip",
    "next one",
    "Continue",
    "Create a new account",
    "Telephone number",
    "email",
    "By clicking on register, you acknowledge that you have read the privacy policy and agree to the terms of the application",
    "Sign Up",
    "do you have an account?",
    "Log in now",
    "The phone number is already registered. Please use another phone number or login",
    "The email is registered by one of the users. Please change email",
    "The service is not available in your country",
    "Please enter the email correctly",
    "Confirm phone number",
    "verify your e-mail",
    "Please enter the code sent to the email listed to activate it",
    "Please enter the code sent to the mobile number",
    "Resend",
    "emphasis",
    "Okay",
    "Unfortunately, the activation code is not valid. Please try again or resend the code",
    "Please wait a while before sending the code again",
    "A 6-digit code has been sent to the following mobile number",
    "A 4-digit code has been sent to the following email",
    "An unexpected error occurred. Please try again later",
    "Don't have an account?",
    "Register now",
    "sign in",
    "The mobile number is not allowed to login.\nPlease change your mobile number or select the appropriate country",
    "Good night",
    "Enter your name here",
    "Done",
    "My requests",
    "Previous chats",
    "my products",
    "Favorite Products",
    "Preferred Service Providers",
    "Subscription information",
    "Why subscribe to the WeTech app?",
    "more details",
    "Main",
    "Our services",
    "notifications",
    "More",
    "Edit profile",
    "Select Language",
    "Arabic",
    "EN",
    "Talk to sellers",
    "The service of calling the service provider outside the application. For customers subscribed to the application only, you can chat with the service provider or subscribe to the direct calling service",
    "About the department",
    "You don't have any notifications at the moment",
    "Seconds",
    "minutes",
    "Hours",
    "day",
    "Privacy policy",
    "About the application of WeTech",
    "Register as a service provider",
    "Common questions",
    "Support",
    "Share the app",
    "App evaluation",
    "Logout",
    "Share your opinion about the app",
    "add a comment",
    "Please specify how many stars you give to the application first before sending your rating",
    "send",
    "please",
    "If my service suits you, share my work",
    "who are we ?",
    "Connect with us",
    "subscribe now",
    "Sender data",
    "Report a problem",
    "mute notifications",
    "Dear customer, WeTech application is an intermediary between customers and service providers, as the warranty is the guarantee of the service provider you have chosen. Talk to the service provider with all the problem details. The solution. Security",
    "Location",
    "File",
    "Discount code",
    "Picture",
    "Writes ...",
    "Add a discount code",
    "Do you have a discount coupon?",
    "Enter it now to take advantage of the discount",
    "Current orders",
    "Completed orders",
    "Canceled orders",
    "You do not have any request at the moment",
    "Wait",
    "Pending",
    "Completed",
    "Price",
    "Call",
    "You don't have any chats at the moment",
    "specialization in",
    "service",
    "Available",
    "Busy",
    "search here",
    "filter results",
    "All results",
    "filter",
    "Search filters",
    "Choose the city",
    "Choose the neighborhood",
    "Choose Type",
    "Choose the brand",
    "Choose the model",
    "All",
    "Please choose the city first before choosing the neighborhood",
    "Please select the device type first",
    "Please choose the brand first before selecting the model",
    "Filter implementation",
    "Chat",
    "About the service provider",
    "About the service provider",
    "customer reviews",
    "view all",
    "There are no reviews yet for the service provider",
    "OK",
    "not agree",
    "an offer",
    "Choose your preferred payment method",
    "Offer rejected",
    "Add a quote",
    "Offer details",
    "Offer Price",
    "Show canceled",
    "Cancellation",
    "Please cancel the previous offer before adding a new offer",
    "cash",
    "bank card",
    "Follow",
    "Offer accepted",
    "the shop",
    "Offers that interest you",
    "All",
    "Offers",
    "new",
    "used",
    "sell device",
    "Product title",
    "Choose the section",
    "Choose the type of product",
    "Choose the device brand",
    "Product color",
    "Duration of use",
    "memory data",
    "Ad duration",
    "It has a warranty",
    "Device status",
    "Yes",
    "No",
    "Add the product to the offers section",
    "Bid price (optional)",
    "Seller's note",
    "Please choose the section first before choosing the type of product or choosing the brand",
    "Sale offer",
    "Product details",
    "product specification",
    "memory",
    "Seller Feedback",
    "You have not preferred any product yet",
    "displayed",
    "Finished",
    "delete",
    "Modification",
    "Are you sure to delete the product?",
    "Retreat",
    "I recommend this engineer to ",
    "WeTech app  for maintenance, technical and business services ❤️", 
    "Service provider subscription request",
    "product modification",
    "save",
    "Order details",
    "Receipt of the request",
    "Cancelling order",
    "Are you sure to check out?",
    "Finish and add a rating",
    "Add a review",
    "Canceled",
    "my balance",
    "Your current balance",
    "Financial transactions",
    "You do not have any financial transactions at the moment.",
    "Withdraw the balance of a transaction number",
    "Profit from Offer No.",
    "Balance withdrawal",
    "shoot",
    "Enter an active PayPal account to withdraw the balance to it",
    "Withdrawal confirmation",
    "E-mail",
    "Select the value of the balance to withdraw",
    "Are you sure you want to drag * to e-mail #?",
    "Confirmation of balance withdrawal",
    "A verification code has been sent to your account email to confirm the operation. Enter the code sent to this",
    "service type",
    "Choose subcategory",
    "Add company type",
    "Add service type",
    "Please select the type of maintenance service first",
    "Please select a subcategory first",
    "First Name",
    "Second name",
    "last name",
    "ID mobile number *",
    "* Close to first class",
    "ID photo upload",
    "send data",
    "Your request has been sent successfully. And it will be reviewed by one of the hosts. You can review the status of the application at any time",
    "You have previously submitted add services",
    "Order status",
    "pending",
    "under review",
    "It has been accepted",
    "rejected",
    "Choose the type of package you prefer",
    "days",
    "Apple Store",
    "Google Store",
    "Paypal",
    "Use the coupon",
    "The discount code you entered is not valid",
    "You have a great discount",
    "Pay by bank card",
    "Current Subscription",
    "The number of days left",
    "Subscription renewal",
    "Experience",
    "the performance",
    "respect the time",
    "Spread",
    "Please add your review first.",
    "The service has been evaluated successfully",
    "You have already rated the service",
    "You do not have a credit balance on the account",
    "The operation has been canceled by the user",
    "You do not have any withdrawable balance",
    "Inquiries and complaints",
    "The name",
    "Address",
    "phone",
    "email",
    "Briefly explain the details of the problem",
    "The complaint has been sent successfully. The complaint will be reviewed shortly. Thanks",
    "My Services",
    "My Chats",
    "You don't have any added services at the moment",
    "You can add services here",
    "add service",
    "service modification",
    "Service name",
    "Subsection",
    "Please select the main section first",
    "Service description",
    "Service Gallery",
    "add offer",
    "Offer Description",
    "Publish the service",
    "You have not added any special offers to the service yet",
    "Please add description and price for the offer",
    "Service offer",
    "I recommend you to try this service",
    "There are no special offers yet",
    "Status",
    "My data",
    "Specialization",
    "Site",
    "Brief about me",
    "business services",
    "Services search filters",
    "Service Provider Rating",
    "Enter your phone number",
    "This number does not have a service provider account yet, you can contact us through our website for any inquiries, thank you",
    "account closing",
    "Your account will be permanently deleted\nAre you sure you want to delete your account?",
    "Attention",
    "You did not make any changes to save.",
    "Enter your email here",
    "Category",
    "the country not found",
    "user registered successfully",
    "user was logged in",
    "logout successful",
    "user updated  successfully",
    "We are pleased to have you join us\nAll you have to do is download provider app\nThen create your account and\nstart selling your services",
    "Download provider app",
    "Describe your experience (optional)",
    "Good morning",
    "Soon..",
    "Order delivery",
    "Are you sure to deliver the order?",
    "Are you sure to cancel the order?",
    "Write the reason...",
    "Must Login Firstly",
    "Succesful order create, you can show order in Current orders",
    "Show me",
    "Report sales",
    "Pay commission order number",
    "Implementation order",
    "Total sales",
    "App commission",
    "Net sales",
    "after discount",
    "Commission WeTech",
    "Services",
    "Brands",
    "Please select country first",
    "Select Country",
    "The terms of service have been violated and the account suspended.",
    "Please update your WeTech's application to get a great copy",
    "There is a new version with new and great features!",
    "Update",
    "Later",
    "* Very important: The use of Apple devices maintenance voids the warranty of Apple, and the parts used are not original.",
    "Are you sure you want to log out?",
    "To ensure the quality of service, numbers are not allowed to be exchanged",
    "https://apps.drtechapp.com/",
    "You have previously submitted an amendment request for the service:",
    "The service will be transferred to review by the administration \ nAre you sure to send the modification request?",
    "In all our global branches for your WeTech",
    "in all areas",
    "general",
    "All services",
    "Service Providers",
    "Sorry, you can't send more offers!\nBecause the debt limit has been reached\n",
    "Enter a profile that attracts customers",
    "The provider sent an offer\nand is waiting for the customer to accept or reject",
    "Please enter the phone number correctly",
    "We have blocked all requests from this device due to unusual activity. Try again later.",
    "Withdrawing a commission from the WeTech platform",
    "take photo",
    "Sort By",
    "most religious",
    "best seller",
    "most crowded",
    "most canceled",
    "the most recent",
    "Are you having trouble getting the code?",
    "push through",
    "Accurate",
    "hour",
    "Subscription benefits",
    "the remaining time",
    "For subscribers only",
    "The provider you chose to communicate with is currently busy, you can communicate with the rest of the available providers or come back later, unless you have a prior request. You can contact him from my requests page or from previous chats",
    "Order it",
    "Hello, can I have this offer: (%s)",
    "offer number",
    "Offers",
    "Offers for this service",
    "Are you sure to delete the offer? ",
    "offer modification",
    "This offer is for customers subscribed to the application only. You can take advantage of my offers or subscribe to benefit from the express offer",
    "you can call",
    "Working",
    "Pause (This offer is no longer available)",
    "Profits from your services",
    "The server cannot be contacted, are you sure you are connected?",
    "Are you sure you want to delete the service?",
    "You don't have any reports at the moment",
    "Customer",
    "Provider",
    "Is it resolved?",
    "Pay the order price #",
    "Add balance to transaction number #",
    "Add balance",
    "Set Amount",
    "Add",
    "The balance you want to withdraw is greater than the amount available in your account, please enter a value that matches or is less than the available balance",
    "Your request has been successfully sent for review by the administration, the balance will be sent within 24 hours if the information entered is correct",
    "This content is against",
    "Is this content in violation of the terms of use?",
    "Write the reason for the violation to the user of the application...",
    "contrary",
    "Are you sure you want to delete this violation?",
    "Infraction",
    "withdrawal requests",
    "Has the amount been transferred?\nIf you press Yes, a notification will be sent to the user that the transfer has been successful",
    "most profitable",
    "most infringing",
    "the support",
    "requests",
    "The content does not comply with the terms of the application",
    "send a cancellation request",
    "Waiting for\nCancellation",
    "Service Completion Request",
    "Reason for canceling the order",
    "Reason for canceling the request",
    "Evaluations",
    "Published Services",
    "completed applications",
    "Requests in progress",
    "date of registration",
    "Country",
    "documents",
    "Personal Identification",
    "Experiences",
    "The provider has not added his account",
    "View Provider Information",
    "Repair request",
    "Determined after preview",
    "Add your profile picture\nto increase your chance of getting more sales",
    "Visit my profile",
    "Direct call service for subscribers only\n\nYou can request the service directly from the service provider without subscribing and the provider will contact you as soon as \n\nor subscribe to the direct call service and then communicate with all providers in all sections and services for free....",
    "Direct Maintenance Request",
    "Link to your twitter account",
    "Link to your facebook account",
    "Link to your account on Telegram",
    "Link to your instagram account",
    "social media pages",
    "The service of obtaining social networking accounts for providers is for subscribers only, you can subscribe to the application",
    "You haven't added any skills yet",
    "skill number",
    "Are you sure you want to delete this experience?",
    "You do not have any services belonging to the Business Services Department to send offers on",
    "You have a previous request for the same service\nYou can view it in the My Current Requests section",
    "Enter the cost of the order...",
    "Thank you for trusting me,\nI confirm your request so that I can serve you",
    "Call the technician",
    "No experience added yet for the service provider",
    "Terms of use",
    "Order number #",
    "Create request:",
    "Last update of the request:",
    "show above",
    "users",
    "providers",
    "Client",
    "watchers",
    "Control Panel",
    "visited my profile",
    "ID photos",
    "There is no",
    "OS",
    "The last date on which the account was opened",
    "User Balance",
    "debt ceiling",
    "to share",
    "Supplier Offers",
    "voice call",
    "Addmin",
    "request offer",
    "Choose City",
    "The service has been successfully added to my favorite services, you can view it in the Favorite Services section",
    "You have not preferred any service yet",
    "There is no permission to do this!",
    "Offer Store",
    "Product Description",
    "The product has been successfully ordered, you can follow it in the My requests section",
    "product price",
    "product shipping",
    "Total",
    "Sale",
    "Product Purchase Confirmation",
    "Write your address in detail:",
    "Enter another phone number to contact:",
    "Invoice details:",
    "There are no products for this section at the moment, it will be added later..",
    "best seller",
    "daily specials",
    "tax included",
    "off",
    "continue",
    "English title of the product",
    "You have submitted a request to add a product",
    "You have submitted a product modification request.",
    "The product will be submitted for review by management\nAre you sure to send a modification request?",
    "This product cannot be exchanged or returned.",
    "payment fee",
    "technical advisor",
    "Hello, can you help me?",
    "Telling the consultant about your city \nhelps speed up your service:",
    "Enter where is your city?",
    "swipe to cancel",
    "Press the lock to stop",
    "Send a file...", 
    "a file couldn't be sent!",
    "Subscribe and communicate with technicians",
    "The engineer's service you went to is no longer available, ask the technical advisor to send you another engineer's service, we are happy to serve you",
    "Sliders",
    "immediate maintenance request",
    "ready maintenance offers",
    "Maintenance Request",
    "Device type",
    "Model",
    "You must choose",
    "first",
    "Color",
    "There are currently no colors.",
    "Problem",
    "City",
    "There are currently no cities.",
    "You must select the type of device first.",
    "There are currently no models.",
    "There are no problems at the moment.",
    "Street",
    "There are currently no survivors.",
    "Notes",
    "search here",
    "Choose the right technician",
    "You must complete the application and fill in all the fields first, so that the appropriate technician appears for you.",
    "You must choose a service technician first.",
    "Next",
    "Choose what you see fit",
    "Technical Profile",
    "Connected",
    "not connected",
    "Including installation",
    " S.R",
    'amount including tax',
    "Your request has been successfully submitted, you can view it in the My Current Requests section",
    "Order details",
    "Taxes included ",
    "Payment upon receipt",
    "prepaid",
    "Discount Code",
    "Remaining after maintenance",
    "Fees after maintenance",
    "Total",
    "Maintenance technician name",
    "Note: We Tech has the right to change the technician if the service is not implemented.",
    "The discount code has been activated successfully.",
    "Unfortunately, the discount code you used has expired.",
    "The discount code is currently invalid.",
    "There was an error in the discount code you used, please check it and try again.",
    "You must choose a payment method first.",
    "Checkout",
    "activation",
    "Discount code",
    "Total order",
    "Left",
    "https://wetech.drtech-api.com/",
    "I advise you to try this product of",
    "You must select a bid first.", 
    "to be determined after inspection",
    "The provider you have chosen is currently busy with another customer. You can deal with the rest of the available suppliers or come back later, unless you have a pre-order, so you can contact him from the My Orders page.",
    "There is no maintenance technician for the service I chose in the neighborhood",
    "Login",
    "Request a free examination",
];